### ISSUE TITLE
茅台只能手机端下单，是不是不一样的？

### ISSUE THREAD

**Issue by linxuchuan** [JerryAZR/InstaOrder#1]
商品id：100012043978
虽然还没试过，但是我看你b站里面那个第一个评论说mt抢到之后没有订单。是不是就是因为下单方式不一样。

**Comment by JerryAZR** [comment]
只能手机端下单的我这个软件是不行的。它本质上就是个网页端的自动化

**Comment by linxuchuan** [comment]
好吧，那看来茅台是不行了。其他东西我再试试。

**Comment by cheng990704** [comment]
能不能单独发一个有exe邮件的到我邮箱czp0704@163.com，只想抢一个相机抢了好久了谢谢up主不是黄牛，b站已经关注你了。万分感谢！！！！！
